name: Lints

on: [push, pull_request]

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer le lint HTML
        run: npx htmlhint "**/*.html"